// Code generated by protoc-gen-go-http. DO NOT EDIT.

package task

import (
	http "github.com/infraboard/mcube/pb/http"
)

// HttpEntry todo
func HttpEntry() *http.EntrySet {
	set := &http.EntrySet{
		Items: []*http.Entry{
			{
				GrpcPath:         "/workflow.task.Service/RunPipeline",
				FunctionName:     "RunPipeline",
				Path:             "/pipeline_tasks/",
				Method:           "POST",
				Resource:         "pipeline_task",
				AuthEnable:       true,
				PermissionEnable: true,
				AuditLog:         false,
				Labels:           map[string]string{"action": "create"},
			},
			{
				GrpcPath:         "/workflow.task.Service/QueryPipelineTask",
				FunctionName:     "QueryPipelineTask",
				Path:             "/pipeline_tasks/",
				Method:           "GET",
				Resource:         "pipeline_task",
				AuthEnable:       true,
				PermissionEnable: false,
				AuditLog:         false,
				Labels:           map[string]string{"action": "list"},
			},
		},
	}
	return set
}
