// Code generated by protoc-gen-go-http. DO NOT EDIT.

package deploy

import (
	http "github.com/infraboard/mcube/pb/http"
)

// HttpEntry todo
func HttpEntry() *http.EntrySet {
	set := &http.EntrySet{
		Items: []*http.Entry{
			{
				Path:         "/workflow.deploy.Service/CreateApplicationDeploy",
				FunctionName: "CreateApplicationDeploy",
			},
			{
				Path:         "/workflow.deploy.Service/QueryApplicationDeploy",
				FunctionName: "QueryApplicationDeploy",
			},
		},
	}
	return set
}
