// Code generated by github.com/infraboard/mcube
// DO NOT EDIT

package action

import (
	"bytes"
	"fmt"
	"strings"
)

// ParseRUNNER_TYPEFromString Parse RUNNER_TYPE from string
func ParseRUNNER_TYPEFromString(str string) (RUNNER_TYPE, error) {
	key := strings.Trim(string(str), `"`)
	v, ok := RUNNER_TYPE_value[strings.ToUpper(key)]
	if !ok {
		return 0, fmt.Errorf("unknown RUNNER_TYPE: %s", str)
	}

	return RUNNER_TYPE(v), nil
}

// Equal type compare
func (t RUNNER_TYPE) Equal(target RUNNER_TYPE) bool {
	return t == target
}

// IsIn todo
func (t RUNNER_TYPE) IsIn(targets ...RUNNER_TYPE) bool {
	for _, target := range targets {
		if t.Equal(target) {
			return true
		}
	}

	return false
}

// MarshalJSON todo
func (t RUNNER_TYPE) MarshalJSON() ([]byte, error) {
	b := bytes.NewBufferString(`"`)
	b.WriteString(strings.ToUpper(t.String()))
	b.WriteString(`"`)
	return b.Bytes(), nil
}

// UnmarshalJSON todo
func (t *RUNNER_TYPE) UnmarshalJSON(b []byte) error {
	ins, err := ParseRUNNER_TYPEFromString(string(b))
	if err != nil {
		return err
	}
	*t = ins
	return nil
}
