// Code generated by github.com/infraboard/mcube
// DO NOT EDIT

package application

import (
	"bytes"
	"fmt"
	"strings"
)

// ParseSCM_TYPEFromString Parse SCM_TYPE from string
func ParseSCM_TYPEFromString(str string) (SCM_TYPE, error) {
	key := strings.Trim(string(str), `"`)
	v, ok := SCM_TYPE_value[strings.ToUpper(key)]
	if !ok {
		return 0, fmt.Errorf("unknown SCM_TYPE: %s", str)
	}

	return SCM_TYPE(v), nil
}

// Equal type compare
func (t SCM_TYPE) Equal(target SCM_TYPE) bool {
	return t == target
}

// IsIn todo
func (t SCM_TYPE) IsIn(targets ...SCM_TYPE) bool {
	for _, target := range targets {
		if t.Equal(target) {
			return true
		}
	}

	return false
}

// MarshalJSON todo
func (t SCM_TYPE) MarshalJSON() ([]byte, error) {
	b := bytes.NewBufferString(`"`)
	b.WriteString(strings.ToUpper(t.String()))
	b.WriteString(`"`)
	return b.Bytes(), nil
}

// UnmarshalJSON todo
func (t *SCM_TYPE) UnmarshalJSON(b []byte) error {
	ins, err := ParseSCM_TYPEFromString(string(b))
	if err != nil {
		return err
	}
	*t = ins
	return nil
}
