// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.1
// source: api/apps/approval/pb/approval.proto

package approval

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ServiceClient is the client API for Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServiceClient interface {
	CreateBook(ctx context.Context, in *CreateApprovalRequest, opts ...grpc.CallOption) (*Approval, error)
	QueryBook(ctx context.Context, in *QueryApprovalRequest, opts ...grpc.CallOption) (*ApprovalSet, error)
	DescribeBook(ctx context.Context, in *DescribeApprovalRequest, opts ...grpc.CallOption) (*Approval, error)
	UpdateBook(ctx context.Context, in *UpdateApprovalRequest, opts ...grpc.CallOption) (*Approval, error)
	DeleteBook(ctx context.Context, in *DeleteApprovalRequest, opts ...grpc.CallOption) (*Approval, error)
}

type serviceClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceClient(cc grpc.ClientConnInterface) ServiceClient {
	return &serviceClient{cc}
}

func (c *serviceClient) CreateBook(ctx context.Context, in *CreateApprovalRequest, opts ...grpc.CallOption) (*Approval, error) {
	out := new(Approval)
	err := c.cc.Invoke(ctx, "/infraboard.workorder.approval.Service/CreateBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) QueryBook(ctx context.Context, in *QueryApprovalRequest, opts ...grpc.CallOption) (*ApprovalSet, error) {
	out := new(ApprovalSet)
	err := c.cc.Invoke(ctx, "/infraboard.workorder.approval.Service/QueryBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) DescribeBook(ctx context.Context, in *DescribeApprovalRequest, opts ...grpc.CallOption) (*Approval, error) {
	out := new(Approval)
	err := c.cc.Invoke(ctx, "/infraboard.workorder.approval.Service/DescribeBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) UpdateBook(ctx context.Context, in *UpdateApprovalRequest, opts ...grpc.CallOption) (*Approval, error) {
	out := new(Approval)
	err := c.cc.Invoke(ctx, "/infraboard.workorder.approval.Service/UpdateBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) DeleteBook(ctx context.Context, in *DeleteApprovalRequest, opts ...grpc.CallOption) (*Approval, error) {
	out := new(Approval)
	err := c.cc.Invoke(ctx, "/infraboard.workorder.approval.Service/DeleteBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceServer is the server API for Service service.
// All implementations must embed UnimplementedServiceServer
// for forward compatibility
type ServiceServer interface {
	CreateBook(context.Context, *CreateApprovalRequest) (*Approval, error)
	QueryBook(context.Context, *QueryApprovalRequest) (*ApprovalSet, error)
	DescribeBook(context.Context, *DescribeApprovalRequest) (*Approval, error)
	UpdateBook(context.Context, *UpdateApprovalRequest) (*Approval, error)
	DeleteBook(context.Context, *DeleteApprovalRequest) (*Approval, error)
	mustEmbedUnimplementedServiceServer()
}

// UnimplementedServiceServer must be embedded to have forward compatible implementations.
type UnimplementedServiceServer struct {
}

func (UnimplementedServiceServer) CreateBook(context.Context, *CreateApprovalRequest) (*Approval, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBook not implemented")
}
func (UnimplementedServiceServer) QueryBook(context.Context, *QueryApprovalRequest) (*ApprovalSet, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryBook not implemented")
}
func (UnimplementedServiceServer) DescribeBook(context.Context, *DescribeApprovalRequest) (*Approval, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DescribeBook not implemented")
}
func (UnimplementedServiceServer) UpdateBook(context.Context, *UpdateApprovalRequest) (*Approval, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBook not implemented")
}
func (UnimplementedServiceServer) DeleteBook(context.Context, *DeleteApprovalRequest) (*Approval, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteBook not implemented")
}
func (UnimplementedServiceServer) mustEmbedUnimplementedServiceServer() {}

// UnsafeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServiceServer will
// result in compilation errors.
type UnsafeServiceServer interface {
	mustEmbedUnimplementedServiceServer()
}

func RegisterServiceServer(s grpc.ServiceRegistrar, srv ServiceServer) {
	s.RegisterService(&Service_ServiceDesc, srv)
}

func _Service_CreateBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateApprovalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).CreateBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/infraboard.workorder.approval.Service/CreateBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).CreateBook(ctx, req.(*CreateApprovalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_QueryBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryApprovalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).QueryBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/infraboard.workorder.approval.Service/QueryBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).QueryBook(ctx, req.(*QueryApprovalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_DescribeBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeApprovalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).DescribeBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/infraboard.workorder.approval.Service/DescribeBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).DescribeBook(ctx, req.(*DescribeApprovalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_UpdateBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateApprovalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).UpdateBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/infraboard.workorder.approval.Service/UpdateBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).UpdateBook(ctx, req.(*UpdateApprovalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_DeleteBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteApprovalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).DeleteBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/infraboard.workorder.approval.Service/DeleteBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).DeleteBook(ctx, req.(*DeleteApprovalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Service_ServiceDesc is the grpc.ServiceDesc for Service service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Service_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "infraboard.workorder.approval.Service",
	HandlerType: (*ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBook",
			Handler:    _Service_CreateBook_Handler,
		},
		{
			MethodName: "QueryBook",
			Handler:    _Service_QueryBook_Handler,
		},
		{
			MethodName: "DescribeBook",
			Handler:    _Service_DescribeBook_Handler,
		},
		{
			MethodName: "UpdateBook",
			Handler:    _Service_UpdateBook_Handler,
		},
		{
			MethodName: "DeleteBook",
			Handler:    _Service_DeleteBook_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/apps/approval/pb/approval.proto",
}
