// Code generated by protoc-gen-go-http. DO NOT EDIT.

package pipeline

import (
	http "github.com/infraboard/mcube/pb/http"
)

// HttpEntry todo
func HttpEntry() *http.EntrySet {
	set := &http.EntrySet{
		Items: []*http.Entry{
			{
				GrpcPath:         "/workflow.pipeline.Service/CreatePipeline",
				FunctionName:     "CreatePipeline",
				Path:             "/pipelines/",
				Method:           "POST",
				Resource:         "pipeline",
				AuthEnable:       true,
				PermissionEnable: true,
				AuditLog:         false,
				Labels:           map[string]string{"action": "create"},
			},
			{
				GrpcPath:         "/workflow.pipeline.Service/QueryPipeline",
				FunctionName:     "QueryPipeline",
				Path:             "/pipelines/",
				Method:           "GET",
				Resource:         "pipeline",
				AuthEnable:       true,
				PermissionEnable: false,
				AuditLog:         false,
				Labels:           map[string]string{"action": "list"},
			},
			{
				GrpcPath:         "/workflow.pipeline.Service/CreateAction",
				FunctionName:     "CreateAction",
				Path:             "/actions/",
				Method:           "POST",
				Resource:         "action",
				AuthEnable:       true,
				PermissionEnable: true,
				AuditLog:         false,
				Labels:           map[string]string{"action": "create"},
			},
			{
				GrpcPath:         "/workflow.pipeline.Service/QueryAction",
				FunctionName:     "QueryAction",
				Path:             "/actions/",
				Method:           "GET",
				Resource:         "action",
				AuthEnable:       true,
				PermissionEnable: false,
				AuditLog:         false,
				Labels:           map[string]string{"action": "list"},
			},
		},
	}
	return set
}
